#ifndef __PARTICLE_QUEUE_H
#define __PARTICLE_QUEUE_H

#define PIXEL_SCREEN_WIDTH 320
#define PIXEL_SCREEN_HEIGHT 200

#define PIXEL_WORLD_WIDTH (PIXEL_SCREEN_WIDTH * 8)
#define PIXEL_WORLD_HEIGHT (PIXEL_SCREEN_HEIGHT)

#endif

